remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

author: [Gravity Admins]

copyright:
  since: false # like: 2000
  revision: false # is show the revision
  
gems:
  - jemoji
